### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by FMotoCar** [Gregor-Agnes/mask_kesearch_indexer#1]
Nachdem ich die Extension Installiert habe, bekomme ich diese Fehlermeldung, deaktiviere ich die extension ist die Fehlermeldung weg, aberv in der Inexierung sehe ich dann mit Mask erstellten Contente nicht, Würde mich auf eine Lösung freuen.

![4](https://user-images.githubusercontent.com/61830792/83256836-786f4f00-a1b3-11ea-8955-92a661d11963.jpg)

**Comment by Gregor-Agnes** [comment]
Sorry, I didn't get this one: Have you really a mask-Element called "tx_mask_I or l" ? If not, you should delete it from the list.

**Comment by Gregor-Agnes** [comment]
Should be fixed with aecbf67bba57941c498fc06847114867ff6864b0
