### ISSUE TITLE
Mask 8.0x Compatibility ?

### ISSUE THREAD

**Issue by micha68g** [Gregor-Agnes/mask_kesearch_indexer#14]
Hi, just a quick question for my understanding:
Actual Dependencies in TER includes: mask (7.0.21 - 7.0.99)

I´m using Mask ^7.1 and even 8.0x. in some of my actual projects with TYPO3 11.5.x / kesearch 4.5x / 4.6.x

I was overriding the Warning-Prompt when installing mask_kesearch_indexer 2.2.1 on TYPO3 11.5.x with newer versions of Mask (e.g. 8.05.)...
So far it seems to work fine despite the lower dependencies.... 
Are there any known issues I could experience in Mask-Versions higher than those in the dedependencies ?

Thanks
Michael

**Comment by Gregor-Agnes** [comment]
Thx for the feedback. No issues known so far.  I should publish an updated version soon.

If you experience any problems, please let me know! :)

**Comment by Gregor-Agnes** [comment]
Fixed with https://github.com/Gregor-Agnes/mask_kesearch_indexer/commit/b057cf8c76d3192006c9ef4860ba1b509430d97b
