### ISSUE TITLE
ke_search requirement in ext_emconf.php and composer.json differ

### ISSUE THREAD

**Issue by christianbltr** [Gregor-Agnes/mask_kesearch_indexer#2]
Hey, first of all thanks for adding a mask in indexer to ke_search!

The version requirements set in ext_emconf.php and in composer.json differ.

It is not possible to install mask_kesearch_indexer together with ke_search 3.2.0 if you look at ext_emconf.php. But the extension works with ke_search 3.2.0 and composer.json allows this also.

The version requirement in ext_emconf.php should be
`'ke_search' => '3.1.0-3.99.99',`

**Comment by Gregor-Agnes** [comment]
Thx for the pull request. I rather added compatibility for until ke_search 3.2.99 since this is the newest release and you tested that 👍

**Comment by christianbltr** [comment]
OK, I understand. But you did the same with the requirement to mask and with the requirement in composer.json for both (mask and ke_search).

I do not expect any big architectural changes in ke_search 3.X.

In fact, ke_search 3.3 will com quite soon in the next weeks and then again mask_kesearch_indexer will be incompatible again.

**Comment by Gregor-Agnes** [comment]
Ok, I will take the risk :) and release a version compatible untill 3.9.x
