### ISSUE TITLE
Mask ^6 compatibility

### ISSUE THREAD

**Issue by h3nn3s** [Gregor-Agnes/mask_kesearch_indexer#6]
Currently master composer.json is made compatible to current mask versions.

At least one point is missing: ext_emconf.php 

I did not test the functionallity of this extension with mask v6, yet.
After testing I would provide a PR for this issue.

**Comment by h3nn3s** [comment]
yeah - thanks for your release of v1.6.4.
I did not experience any issues so far with most current Mask version

**Comment by Gregor-Agnes** [comment]
Nice and thx for reporting!
