### ISSUE TITLE
Tag 2.0.0

### ISSUE THREAD

**Issue by kszymukowicz** [Gregor-Agnes/mask_kesearch_indexer#9]
hi

seems like master is stable. 
Any chance to tag 2.0.0?

**Comment by Gregor-Agnes** [comment]
Hm, there was a tag 2.0.0. 
New version is 2.1.0

**Comment by kszymukowicz** [comment]
Sry - my fault. 
Thats because of tags naming.
I saw it like that and though you forget to tag 2.0.0

<img width="505" alt="image" src="https://user-images.githubusercontent.com/1453553/154051211-3565da9b-1890-48f5-8f34-72a93abd5385.png">
